# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField()),
                ('low_res_url', models.URLField(max_length=500)),
                ('embed_code', models.CharField(max_length=3000)),
            ],
        ),
    ]
